### ISSUE TITLE
Allow for local versions for the Cost and Fee fields

### ISSUE THREAD

**Issue by bobbingwide** [bobbingwide/oik-weight-zone-shipping#11]
The shipping rate table is entered in a pseudo CSV format, allowing a variety of separators including comma. It does not support the Max weight or Cost being entered in a local version where the decimal separator is a comma.  The help for the field mentions this.  
 
Set your weight based rates in %1$s for this shipping zone (one per line).<br /> Format: Max weight|Cost|Method Title override<br />Example: 10|6.95|Standard rate <br />For decimal, use a dot not a comma.

### Requirement
Allow for localized content in the shipping rate table.

### Proposed solution
- Provide a more flexible method of parsing the shipping rate table.
- Update the help text to reflect this.

**Comment by bobbingwide** [comment]
When a new version is delivered, regardless of which version is the new version, we'll need to perform some checks to ensure that the logic will continue to work with the user defined separators. 
It would also be nice if we could cater for both the defined separators and the defaults.

**Comment by ale5000-git** [comment]
I think it would be safer in this way:
- Internally store only "."
- When saving values convert user separator (the one defined in woocommerce settings) to "." - Example: 10|6,95|Standard rate => 10|6.95|Standard rate 
- When displaying values convert "." to user separator (the one defined in woocommerce settings) - Example: 10|6.95|Standard rate => 10|6,95|Standard rate
- When using values internally just use "."

So the internal data is always the same for all users and it change only the displayed value.

**Comment by bobbingwide** [comment]
The Handling fee should also cater for the local version of the decimal separator.

**Comment by bobbingwide** [comment]
The Max weight field, which is not a currency amount should not be limited in the same way as the cost field, specifically the number of decimal places.

**Comment by bobbingwide** [comment]
In order to support upgrading from a previous version and switching between plugins running different versions it seems necessary to implement the `rates` as a new field and not to override the existing `options` field. 

We will need to make use of a `rates_table` so that the data can be stored as an array but still displayed in a textarea.

This solution should also support downgrading to a previous version, although we don't expect the `options` string to have been updated if the `rates_table` has been changed.

Since the `fee` field is simpler we should be able to get away with just having one version, always storing the value as a decimal, with a period for the decimal point.

**Comment by bobbingwide** [comment]
The code also needs to cater for the Method title override containing characters that cause them to be escaped with backslashes when inserted into the database. ie. We need to run stripslashes() against the textarea field and anywhere else that may require it.
