### ISSUE TITLE
Big problem and crash with the last version 0.2.0

### ISSUE THREAD

**Issue by calyweb** [bobbingwide/oik-weight-zone-shipping#27]
Hi,

With your last version 0.2.0, my website crash entirely, please see the details :

WordPress version 5.6
Thème actuel : Neighborhood Child Theme (version 1.0)
Extension actuelle : oik weight zone shipping (version 0.2.0)
PHP version 7.3.25

Détails de l’erreur
======================
Une erreur de type E_COMPILE_ERROR a été causée dans la ligne 53 du fichier /home/httpd/vhosts/gladiatorfit.ch/httpdocs/shop/wp-content/plugins/oik-weight-zone-shipping/oik-weight-zone-shipping.php. Message d’erreur : require_once(): Failed opening required ‘/home/httpd/vhosts/gladiatorfit.ch/httpdocs/shop/wp-content/plugins/oik-weight-zone-shipping/class-oik-weight-zone-shipping-multi-rate.php’ (include_path=’.:/usr/share/pear:/usr/share/php’)

I had to go back to previous version and it’s okay but can you check why your last version is not working ?? Thanks

**Comment by bobbingwide** [comment]
Hi, sorry about that. I'll do some tests to find out what's missing.

**Comment by calyweb** [comment]
Thanks,

I posted the same message on wordpress support, and we are a lot to have the same problem...

Yohann Cremonese
STUDIO CALYWEB
06 73 87 65 88
contact@calyweb.com
www.calyweb.com
Gujan-Mestras

**Comment by bobbingwide** [comment]
Oops, I failed to commit two new files to SVN.

**Comment by bobbingwide** [comment]
I've delivered v0.2.1 to wordpress.org. Please update and confirm. Thanks

**Comment by bobbingwide** [comment]
Yohann replied:

Thanks for the quick support !
It’s working perfectly now !
Many thanks again 

So closing now.
