### ISSUE TITLE
Critical error on last version 0.2.0

### ISSUE THREAD

**Issue by nunoalex46** [bobbingwide/oik-weight-zone-shipping#28]
The website is not working anymore since your plugin was updated to version 0.2.0
I had to disable the plugin, but is also showing problems in the checkout.
I can't find the previous version to install...
Please can you check the problem as soon as possible.
Thanks.
Merry Christmas.

**Comment by bobbingwide** [comment]
Sorry about that. I'd forgotten to commit two new files to the SVN repository.
This is now resolved with v0.2.1 available from wordpress.org

> I can't find the previous version to install...

For future reference.

The previous version is available from https://wordpress.org/plugins/oik-weight-zone-shipping/advanced/
See the Previous Versions section in Advanced Options
You can choose to download any version.
eg https://downloads.wordpress.org/plugin/oik-weight-zone-shipping.0.1.3.zip

Previous versions are also available from oik-plugins.com 

See https://www.oik-plugins.com/oik_pluginversion/oik-weight-zone-shipping-v0-1-3/
