### ISSUE TITLE
Use with Local Pickup

### ISSUE THREAD

**Issue by bonaldi69** [bobbingwide/oik-weight-zone-shipping#5]
Can't make it working with Local Pickup activated.
Only shipping zone at first position works.

**Comment by bobbingwide** [comment]
Do you want to try switching to https://GitHub.com/bobbingwide/oik-weight-zone-shipping

**Comment by bonaldi69** [comment]
Works, thanks.
I get an updated French translation, are you interested ?
The actual one is so poor...
Regards.

**Comment by bobbingwide** [comment]
Yes, the actual one was a half hearted attempt using Google translate. All help most appreciated.

**Comment by bonaldi69** [comment]
I try to send you the zip file, but it doesn't work...
I get this message:
Unfortunately, we don’t support that file type. Try again with a PNG, GIF, JPG, DOCX, PPTX, XLSX, TXT, PDF, or ZIP.

But IT IS a ZIP!

**Comment by bobbingwide** [comment]
Hi, can you try cloning this repository, updating the French language .po file, then creating a pull request. https://github.com/bobbingwide/oik-weight-zone-shipping/blob/master/languages/oik-weight-zone-shipping-fr_FR.po

or email the file directly to me: herb@bobbingwide.com

**Comment by bonaldi69** [comment]
I sent you a link to download the .po file.

**Comment by bobbingwide** [comment]
no sign of any link. Where did you send it?

**Comment by spameur** [comment]
http://dl.free.fr/jRmKbQaiy

**Comment by bobbingwide** [comment]
that link doesn't offer me a download option. Can you email it to me?
or create it as a Gist

**Comment by bonaldi69** [comment]
Strange, for me it offers...
I sent it directly by mail at herb@bobbingwide.com

**Comment by bonaldi69** [comment]
I belong to the Official French Translation Team.
If you ask me as a PTE, I can help you for French.
Before you need to do the necessary:

On your plugin acount: https://developer.wordpress.org/plugins/internationalization/how-to-internationalize-your-plugin/

And make this request to Polyglots here: https://make.wordpress.org/polyglots/?resolved=unresolved

Here is the message to post:

Hello Polyglots!
I am the plugin author for Weight zone shipping for WooCommerce 2.6. Please add the following WordPress.org users as translation editors for his locale:

```
#fr_FR – @bonaldi
```

If you have any questions, just comment here. Thank you!

**Comment by bobbingwide** [comment]
I didn't think that was necessary to have to send those requests anymore but I have anyway.

**Comment by bonaldi69** [comment]
You have to send it if you want my help for French on this new version.
I was a translator on your previous plugin Oik Country, which had language projects.
But the Oik Zone is empty: https://translate.wordpress.org/projects/wp-plugins/oik-weight-zone-shipping

**Comment by bobbingwide** [comment]
there seems to be a problem with the automated system. Sent you a Direct Message on slack.
Dominik Schilling pointed me to https://make.wordpress.org/meta/handbook/documentation/translations/#this-plugin-is-not-properly-prepared-for-localization-%e2%80%93-help

I looked at messages in #meta-language-packs but don't understand what's wrong with oik-weight-zone-shipping

**Comment by bobbingwide** [comment]
OK, the problem with translate.wordpress.org seems to have been resolved. It'll soon not be necessary to deliver the French language version thanks to @spameur

**Comment by bobbingwide** [comment]
The French language version still being delivered in the version installed from GitHub and oik-plugins. 
I'm going to close this issue now.
